# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyser.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyser.proto\x12\x0ftibava.analyser\"J\n\x0cPluginConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\"Y\n\nPluginInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12/\n\x08settings\x18\x03 \x03(\x0b\x32\x1d.tibava.analyser.PluginConfig\"\x14\n\x12ListPluginsRequest\"@\n\x10ListPluginsReply\x12,\n\x07plugins\x18\x01 \x03(\x0b\x32\x1b.tibava.analyser.PluginInfo2d\n\x08\x41nalyser\x12X\n\x0clist_plugins\x12#.tibava.analyser.ListPluginsRequest\x1a!.tibava.analyser.ListPluginsReply\"\x00\x42\x02P\x01\x62\x06proto3')



_PLUGINCONFIG = DESCRIPTOR.message_types_by_name['PluginConfig']
_PLUGININFO = DESCRIPTOR.message_types_by_name['PluginInfo']
_LISTPLUGINSREQUEST = DESCRIPTOR.message_types_by_name['ListPluginsRequest']
_LISTPLUGINSREPLY = DESCRIPTOR.message_types_by_name['ListPluginsReply']
PluginConfig = _reflection.GeneratedProtocolMessageType('PluginConfig', (_message.Message,), {
  'DESCRIPTOR' : _PLUGINCONFIG,
  '__module__' : 'analyser_pb2'
  # @@protoc_insertion_point(class_scope:tibava.analyser.PluginConfig)
  })
_sym_db.RegisterMessage(PluginConfig)

PluginInfo = _reflection.GeneratedProtocolMessageType('PluginInfo', (_message.Message,), {
  'DESCRIPTOR' : _PLUGININFO,
  '__module__' : 'analyser_pb2'
  # @@protoc_insertion_point(class_scope:tibava.analyser.PluginInfo)
  })
_sym_db.RegisterMessage(PluginInfo)

ListPluginsRequest = _reflection.GeneratedProtocolMessageType('ListPluginsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTPLUGINSREQUEST,
  '__module__' : 'analyser_pb2'
  # @@protoc_insertion_point(class_scope:tibava.analyser.ListPluginsRequest)
  })
_sym_db.RegisterMessage(ListPluginsRequest)

ListPluginsReply = _reflection.GeneratedProtocolMessageType('ListPluginsReply', (_message.Message,), {
  'DESCRIPTOR' : _LISTPLUGINSREPLY,
  '__module__' : 'analyser_pb2'
  # @@protoc_insertion_point(class_scope:tibava.analyser.ListPluginsReply)
  })
_sym_db.RegisterMessage(ListPluginsReply)

_ANALYSER = DESCRIPTOR.services_by_name['Analyser']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _PLUGINCONFIG._serialized_start=35
  _PLUGINCONFIG._serialized_end=109
  _PLUGININFO._serialized_start=111
  _PLUGININFO._serialized_end=200
  _LISTPLUGINSREQUEST._serialized_start=202
  _LISTPLUGINSREQUEST._serialized_end=222
  _LISTPLUGINSREPLY._serialized_start=224
  _LISTPLUGINSREPLY._serialized_end=288
  _ANALYSER._serialized_start=290
  _ANALYSER._serialized_end=390
# @@protoc_insertion_point(module_scope)
