# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shotdetection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shotdetection.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13shotdetection.proto\"7\n\x0cVideoRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x15\n\rvideo_encoded\x18\x02 \x01(\x0c\" \n\rVideoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x0bShotRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"5\n\x0cShotResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x05shots\x18\x02 \x03(\x0b\x32\x05.Shot\"?\n\x04Shot\x12\x0f\n\x07shot_id\x18\x01 \x01(\x05\x12\x13\n\x0bstart_frame\x18\x02 \x01(\x05\x12\x11\n\tend_frame\x18\x03 \x01(\x05\x32g\n\x0cShotDetector\x12-\n\ncopy_video\x12\r.VideoRequest\x1a\x0e.VideoResponse(\x01\x12(\n\tget_shots\x12\x0c.ShotRequest\x1a\r.ShotResponseb\x06proto3'
)




_VIDEOREQUEST = _descriptor.Descriptor(
  name='VideoRequest',
  full_name='VideoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='VideoRequest.video_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='video_encoded', full_name='VideoRequest.video_encoded', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=78,
)


_VIDEORESPONSE = _descriptor.Descriptor(
  name='VideoResponse',
  full_name='VideoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='VideoResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=112,
)


_SHOTREQUEST = _descriptor.Descriptor(
  name='ShotRequest',
  full_name='ShotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='video_id', full_name='ShotRequest.video_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=145,
)


_SHOTRESPONSE = _descriptor.Descriptor(
  name='ShotResponse',
  full_name='ShotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ShotResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shots', full_name='ShotResponse.shots', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=200,
)


_SHOT = _descriptor.Descriptor(
  name='Shot',
  full_name='Shot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shot_id', full_name='Shot.shot_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_frame', full_name='Shot.start_frame', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_frame', full_name='Shot.end_frame', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=265,
)

_SHOTRESPONSE.fields_by_name['shots'].message_type = _SHOT
DESCRIPTOR.message_types_by_name['VideoRequest'] = _VIDEOREQUEST
DESCRIPTOR.message_types_by_name['VideoResponse'] = _VIDEORESPONSE
DESCRIPTOR.message_types_by_name['ShotRequest'] = _SHOTREQUEST
DESCRIPTOR.message_types_by_name['ShotResponse'] = _SHOTRESPONSE
DESCRIPTOR.message_types_by_name['Shot'] = _SHOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoRequest = _reflection.GeneratedProtocolMessageType('VideoRequest', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOREQUEST,
  '__module__' : 'shotdetection_pb2'
  # @@protoc_insertion_point(class_scope:VideoRequest)
  })
_sym_db.RegisterMessage(VideoRequest)

VideoResponse = _reflection.GeneratedProtocolMessageType('VideoResponse', (_message.Message,), {
  'DESCRIPTOR' : _VIDEORESPONSE,
  '__module__' : 'shotdetection_pb2'
  # @@protoc_insertion_point(class_scope:VideoResponse)
  })
_sym_db.RegisterMessage(VideoResponse)

ShotRequest = _reflection.GeneratedProtocolMessageType('ShotRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOTREQUEST,
  '__module__' : 'shotdetection_pb2'
  # @@protoc_insertion_point(class_scope:ShotRequest)
  })
_sym_db.RegisterMessage(ShotRequest)

ShotResponse = _reflection.GeneratedProtocolMessageType('ShotResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOTRESPONSE,
  '__module__' : 'shotdetection_pb2'
  # @@protoc_insertion_point(class_scope:ShotResponse)
  })
_sym_db.RegisterMessage(ShotResponse)

Shot = _reflection.GeneratedProtocolMessageType('Shot', (_message.Message,), {
  'DESCRIPTOR' : _SHOT,
  '__module__' : 'shotdetection_pb2'
  # @@protoc_insertion_point(class_scope:Shot)
  })
_sym_db.RegisterMessage(Shot)



_SHOTDETECTOR = _descriptor.ServiceDescriptor(
  name='ShotDetector',
  full_name='ShotDetector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=267,
  serialized_end=370,
  methods=[
  _descriptor.MethodDescriptor(
    name='copy_video',
    full_name='ShotDetector.copy_video',
    index=0,
    containing_service=None,
    input_type=_VIDEOREQUEST,
    output_type=_VIDEORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_shots',
    full_name='ShotDetector.get_shots',
    index=1,
    containing_service=None,
    input_type=_SHOTREQUEST,
    output_type=_SHOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOTDETECTOR)

DESCRIPTOR.services_by_name['ShotDetector'] = _SHOTDETECTOR

# @@protoc_insertion_point(module_scope)
