# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shotdetection_pb2 as shotdetection__pb2


class ShotDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.copy_video = channel.stream_unary(
                '/ShotDetector/copy_video',
                request_serializer=shotdetection__pb2.VideoRequest.SerializeToString,
                response_deserializer=shotdetection__pb2.VideoResponse.FromString,
                )
        self.get_shots = channel.unary_unary(
                '/ShotDetector/get_shots',
                request_serializer=shotdetection__pb2.ShotRequest.SerializeToString,
                response_deserializer=shotdetection__pb2.ShotResponse.FromString,
                )


class ShotDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def copy_video(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_shots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShotDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'copy_video': grpc.stream_unary_rpc_method_handler(
                    servicer.copy_video,
                    request_deserializer=shotdetection__pb2.VideoRequest.FromString,
                    response_serializer=shotdetection__pb2.VideoResponse.SerializeToString,
            ),
            'get_shots': grpc.unary_unary_rpc_method_handler(
                    servicer.get_shots,
                    request_deserializer=shotdetection__pb2.ShotRequest.FromString,
                    response_serializer=shotdetection__pb2.ShotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ShotDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShotDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def copy_video(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ShotDetector/copy_video',
            shotdetection__pb2.VideoRequest.SerializeToString,
            shotdetection__pb2.VideoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_shots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ShotDetector/get_shots',
            shotdetection__pb2.ShotRequest.SerializeToString,
            shotdetection__pb2.ShotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
