# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import facedetection_pb2 as facedetection__pb2


class FaceDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.detect_faces = channel.unary_unary(
                '/FaceDetector/detect_faces',
                request_serializer=facedetection__pb2.FaceRequest.SerializeToString,
                response_deserializer=facedetection__pb2.FaceResponse.FromString,
                )


class FaceDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def detect_faces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'detect_faces': grpc.unary_unary_rpc_method_handler(
                    servicer.detect_faces,
                    request_deserializer=facedetection__pb2.FaceRequest.FromString,
                    response_serializer=facedetection__pb2.FaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FaceDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def detect_faces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FaceDetector/detect_faces',
            facedetection__pb2.FaceRequest.SerializeToString,
            facedetection__pb2.FaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
